import React, { useState } from 'react';
import ReactMarkdown from 'react-markdown';

interface ResultsViewProps {
  markdown: string;
}

export const ResultsView: React.FC<ResultsViewProps> = ({ markdown }) => {
  const [copied, setCopied] = useState(false);

  const handleCopy = () => {
    navigator.clipboard.writeText(markdown);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="w-full max-w-4xl mx-auto space-y-4 animate-fade-in">
      <div className="flex items-center justify-between mb-2">
        <h2 className="text-2xl font-bold text-white flex items-center gap-2">
          <span className="material-icons text-indigo-400">auto_awesome</span>
          Analysis Result
        </h2>
        <button
          onClick={handleCopy}
          className={`flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-medium transition-all ${
            copied
              ? 'bg-green-500/20 text-green-400 border border-green-500/50'
              : 'bg-slate-700 hover:bg-slate-600 text-white border border-slate-600'
          }`}
        >
          <span className="material-icons text-sm">
            {copied ? 'check' : 'content_copy'}
          </span>
          {copied ? 'Copied to Clipboard' : 'Copy Specification'}
        </button>
      </div>

      <div className="bg-slate-800/50 border border-slate-700 rounded-2xl p-8 shadow-xl overflow-hidden">
        <div className="prose prose-invert prose-indigo max-w-none custom-scrollbar overflow-x-hidden">
            {/* 
                Simple Markdown Renderer 
                In a real app, use 'react-markdown' or similar. 
                For this single-file constraint output, I'll implement a basic display 
                that handles newlines and basic structure if a lib isn't available, 
                but the prompt allows imports. I will assume standard pre-wrap for simplicity 
                to avoid complex dependency issues if react-markdown isn't in the environment,
                but ideally I would use it. I'll use whitespace-pre-wrap which is robust.
            */}
            <div className="whitespace-pre-wrap font-sans text-slate-300 leading-relaxed">
                {markdown}
            </div>
        </div>
      </div>
      
      <div className="flex justify-center pt-8 pb-12">
        <p className="text-slate-500 text-sm text-center">
          Generated by Gemini 3.0 Pro. Always review code specifications before implementation.
        </p>
      </div>
    </div>
  );
};